# Generated by Django 3.1.5 on 2021-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0009_auto_20210121_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='bio_code',
            field=models.CharField(max_length=225, null=True, verbose_name='BioCode'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='country',
            field=models.CharField(max_length=225, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_class',
            field=models.CharField(max_length=225, null=True, verbose_name='class'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=50, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='med_agent',
            field=models.CharField(max_length=225, null=True, verbose_name='Medical Agent'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=225, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='risk_level',
            field=models.CharField(max_length=225, null=True, verbose_name='Risk Level'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warrenty_date',
            field=models.DateField(null=True, verbose_name='End Warrenty Date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_num',
            field=models.IntegerField(),
        ),
    ]
