# Generated by Django 3.1.5 on 2021-01-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0010_auto_20210124_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Company Email')),
                ('phone_num', models.CharField(max_length=225, verbose_name='Phone Number')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.hospital')),
            ],
        ),
    ]
