# Generated by Django 3.1.5 on 2021-01-24 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0013_remove_engineer_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='total_response_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Total_Response Time'),
        ),
    ]
