# Generated by Django 3.1.5 on 2021-01-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0014_engineer_total_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
