# Generated by Django 3.1.5 on 2021-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0015_engineer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Department Name'),
        ),
    ]
