# Generated by Django 3.1.5 on 2021-01-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0018_auto_20210125_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.department'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='current_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.hospital'),
        ),
    ]
