# Generated by Django 3.1.5 on 2021-02-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0019_auto_20210131_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='department',
        ),
        migrations.AddField(
            model_name='engineer',
            name='department',
            field=models.ManyToManyField(to='med.Department'),
        ),
    ]
