# Generated by Django 3.1.5 on 2021-02-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0020_auto_20210201_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_id', models.IntegerField(verbose_name='ID of Equiqment to be Edited')),
                ('status', models.CharField(choices=[('LIVE', 'LIVE'), ('DOWN', 'DOWN')], default='LIVE', max_length=50, verbose_name='Equipment Status')),
                ('name', models.CharField(max_length=225, verbose_name='Equipment Name')),
                ('specs', models.TextField(verbose_name='Technical Specifications and Standards')),
                ('quantity', models.IntegerField()),
                ('serial_num', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=255, null=True, verbose_name='Manufacturer')),
                ('country', models.CharField(max_length=225, null=True, verbose_name='Country')),
                ('model', models.CharField(max_length=225, null=True, verbose_name='Model')),
                ('risk_level', models.CharField(max_length=225, null=True, verbose_name='Risk Level')),
                ('eq_class', models.CharField(max_length=225, null=True, verbose_name='class')),
                ('bio_code', models.CharField(max_length=225, null=True, verbose_name='BioCode')),
                ('med_agent', models.CharField(max_length=225, null=True, verbose_name='Medical Agent')),
                ('delivery_date', models.DateField(null=True, verbose_name='Delivery Date')),
                ('warrenty_date', models.DateField(null=True, verbose_name='End Warrenty Date')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.department')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.hospital')),
            ],
        ),
    ]
