# Generated by Django 3.1.5 on 2021-02-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0021_editedequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedequipment',
            name='eng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.engineer'),
        ),
    ]
