# Generated by Django 3.1.5 on 2021-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0022_editedequipment_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Is approved by manager'),
        ),
    ]
