# Generated by Django 3.1.5 on 2021-04-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0026_auto_20210218_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Equipment Name')),
                ('serial_num', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=255, null=True, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=225, null=True, verbose_name='Model')),
                ('delivery_date', models.DateField(null=True, verbose_name='Delivery Date')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.department')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.hospital')),
            ],
        ),
    ]
