# Generated by Django 3.1.5 on 2021-04-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0027_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Is approved by manager'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('DOWN', 'DOWN')], default='LIVE', max_length=50, verbose_name='Equipment Status'),
        ),
    ]
