# Generated by Django 3.1.5 on 2021-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0029_procedure_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='department',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='model',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='name',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='serial_num',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='status',
        ),
        migrations.AddField(
            model_name='procedure',
            name='electrical_safety',
            field=models.TextField(null=True, verbose_name='electrical safety'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='physical_condition',
            field=models.TextField(null=True, verbose_name='physical condition'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='preformance_testing',
            field=models.TextField(null=True, verbose_name='preformance testing '),
        ),
        migrations.AddField(
            model_name='procedure',
            name='preventive_maintenance',
            field=models.TextField(null=True, verbose_name='preventive maintenance '),
        ),
    ]
