# Generated by Django 3.1.5 on 2021-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0030_auto_20210423_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Is approved by manager'),
        ),
    ]
