# Generated by Django 3.1.5 on 2021-04-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0031_procedure_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.hospital'),
        ),
    ]
