# Generated by Django 3.1.5 on 2021-04-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0032_procedure_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.equipment'),
        ),
    ]
