# Generated by Django 3.1.5 on 2021-04-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210407_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_user',
        ),
    ]
