# Generated by Django 3.1.5 on 2021-04-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_user',
        ),
    ]
