# Generated by Django 3.1.5 on 2021-04-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_user',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
