# Generated by Django 3.1.5 on 2021-01-12 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('REPAIR', 'Repairment of Equipment'), ('TRANSFER', 'Transfer of Equipment'), ('TRAINING', 'Training of using Equipment')], default='REPAIR', max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('OPEN', 'Open Issue'), ('CLOSED', 'Closed Issue')], default='OPEN', max_length=50, verbose_name='Status')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
