# Generated by Django 3.1.5 on 2021-01-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0005_engineer_average_response_time'),
        ('workflow', '0005_auto_20210114_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.doctor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.engineer'),
        ),
    ]
