# Generated by Django 3.1.5 on 2021-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20210114_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='details',
            field=models.TextField(null=True, verbose_name='Problem Details'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='img',
            field=models.ImageField(null=True, upload_to='ticket_images', verbose_name='Equipment Picture'),
        ),
    ]
