# Generated by Django 3.1.5 on 2021-01-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20210124_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='img',
        ),
    ]
